AWSTemplateFormatVersion: 2010-09-09
Description: Default lambda template

Transform: AWS::Serverless-2016-10-31

Parameters: 
  Environment: 
    Description: The name of the deployment environment 
    Type: String
    Default: dev
    AllowedValues: [test, dev, prod]
  
  FunctionName:
    Description: The name of the lambda function
    Type: String

  HandlerName:
    Description: The handler of the lambda function
    Type: String

  LambdaSourcePath:
    Description: The source file of the lambda function
    Type: String


Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${FunctionName}-${Environment}
      Description: Lambda function that sends an email
      Role: !GetAtt Role.Arn
      Runtime: nodejs12.x
      Handler: !Ref HandlerName
      CodeUri: !Ref LambdaSourcePath
    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Application
        Value: Violart

  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${Lambda}"

  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      RoleName: !Sub ${FunctionName}-${Environment}
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Violart

  LogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${FunctionName}-policy-${Environment}
      Roles: [!Ref Role]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !GetAtt Logs.Arn
          - Effect: Allow
            Action: ses:SendEmail
            Resource: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*

Outputs:
  Lambda:
    Description: The created lambda function
    Value: !Ref Lambda
