name: Upload Scripts to S3
on: 
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm i

    - name: Run lint
      run: npm run lint

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-central-1

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        sam package \
          --template-file src/email/lambdas.yml \
          --output-template-file lambdas_packaged.yml \
          --s3-bucket violart --s3-prefix artifacts 
        aws s3 cp lambdas_packaged.yml s3://violart/templates/email/lambdas.yml
        
        sam package \
          --template-file src/email/root.yml \
          --output-template-file root_packaged.yml \
          --s3-bucket violart --s3-prefix artifacts 
        aws s3 cp root_packaged.yml s3://violart/templates/email/root.yml