name: Upload Scripts to S3
on: 
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm i

    - name: Run lint
      run: npm run lint

    - name: Build
      run: npm run build:prod

    - name: Zip 
      uses: papeloto/action-zip@v1
      with:
        files: dist/email
        dest: deploy/email/email.zip
    
    - name: Move files to deploy
      run: |
        mv ./src/email/template.yml ./deploy/email/template.yml
        mv ./src/email/send_email_state_machine.json ./deploy/email/send_email_state_machine.json

    - name: Set up S3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: violart
        DEST_DIR: artifacts
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'deploy'